### ISSUE TITLE
controllo id votazione

### ISSUE THREAD

**Issue by Mprovi** [IngSW-unipv/Progetto-O#21]
Quando inizia una votazione, bisogna controllare che il nome assegnato non esista già

**Comment by MarcoLagalla** [comment]
Risolto, implementato controllo su ogni identificativo tabella. Non sono più possibili elezioni con doppio ID.
Va aggiunto che in ogni caso non veniva creata una seconda tabella in quanto si generava una eccezione di tipo SQL.
